### ISSUE TITLE
My Question

### ISSUE THREAD

**Issue by itspranavajay** [IAmKartoon/ChitandaRobot#1]
are you the owner of this code 😙😙
![Screenshot_2021-07-12-23-07-52-739_com android chrome](https://user-images.githubusercontent.com/86167689/125331804-17c6b580-e366-11eb-8254-476369880b52.jpg)
Why copyright

**Comment by itspranavajay** [comment]
Ans me

**Comment by itspranavajay** [comment]
@IAmKartoon

**Comment by itspranavajay** [comment]
@JayPatel1314 aap sab kya karte rahte hu copyright dar nhi lagta

**Comment by itspranavajay** [comment]
Reply sir

**Comment by Am-Jerry** [comment]
> Reply sir

Yea?
